# -*- coding: utf-8 -*-
"""testsuite1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eijSUQYBqgRSsGD_m08VTgXU2MEVfNnB

# Test spot detection

This is a test suite.
"""

import mlflow
import numpy
import sys
import os

"""Prepare for generating inputs."""
seed = int(sys.argv[1]) if len(sys.argv) > 1 else 123

"""Set physical parameters."""

with mlflow.start_run():
    submitted_run = mlflow.run(".", "step1", parameters={"seed":seed})
    step1 = mlflow.tracking.MlflowClient().get_run(submitted_run.run_id)
    # step1
    inputval1 = int(step1.data.metrics["seedplus1"])
    # step2
    submitted_run_step2 = mlflow.run(".", "step2", parameters={"inputval1":inputval1})
    step2 = mlflow.tracking.MlflowClient().get_run(submitted_run_step2.run_id)
    doubledinput = int(step2.data.metrics["doubledinput"])
    # step3
    submitted_run_step3 = mlflow.run(".", "step3", parameters={"step3inputval1":doubledinput})
    step3 = mlflow.tracking.MlflowClient().get_run(submitted_run_step3.run_id)
    sub3 = int(step3.data.metrics["sub3"])

    # output
    print(inputval1)
    print(doubledinput)
    print(sub3)
    # log    
    mlflow.log_param("seed", seed)

    #mlflow.log_metric("seedplus1", inputval1)
    #mlflow.log_metric("doubledinput", doubledinput)
    #mlflow.log_metric("sub3", sub3)
