name: scopyon
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - scikit-image
  - jupyterlab
  - ipywidgets
  - papermill
  - plotly
  - psutil
  - pip
  - pip:
    - git+git://github.com/ecell/scopyon.git@99436fbfd34bb684966846eba75b206c2806f69c    
    - mlflow>=1.0
    - kaleido
    - azure-storage-blob
    - boto3
