# -*- coding: utf-8 -*-
"""testsuite1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eijSUQYBqgRSsGD_m08VTgXU2MEVfNnB

# Test spot detection

This is a test suite.
"""

import mlflow
import numpy
import sys
import os

"""Prepare for generating inputs."""
runid = sys.argv[1]

"""Set physical parameters."""

with mlflow.start_run():
    generation = mlflow.tracking.MlflowClient().get_run(runid)
    print(generation.data)
    print(generation.info.artifact_uri)
