name: workflow

on:
  push:
    branches:
      - master
      
jobs:
  pytest:
    name: Run image analysis workflow
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python packages
        run: |
          python3 -m pip install -U pip
          python3 -m pip install mlflow toml scikit-image plotly kaleido azure-storage-blob
          python3 -m pip install git+git://github.com/ecell/scopyon.git@99436fbfd34bb684966846eba75b206c2806f69c
      - name: Run workflow
        run: python3 describe_workflow.py
